// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbSciW4YYLHksOP051fI1xu-xNs7k4gg',
    appId: '1:531611309734:web:d4995eadb70c0fa2684667',
    messagingSenderId: '531611309734',
    projectId: 'chat-app-5dccc',
    authDomain: 'chat-app-5dccc.firebaseapp.com',
    storageBucket: 'chat-app-5dccc.appspot.com',
    measurementId: 'G-PK8GJFFXST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXHoQYpZGtachsyx2YkSbym3swjYTbkiw',
    appId: '1:531611309734:android:316639c162b8be02684667',
    messagingSenderId: '531611309734',
    projectId: 'chat-app-5dccc',
    storageBucket: 'chat-app-5dccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4ZlJptOzxG2U9N73Kp4jwzfgBYZZlXY',
    appId: '1:531611309734:ios:498c48258d6f1e5d684667',
    messagingSenderId: '531611309734',
    projectId: 'chat-app-5dccc',
    storageBucket: 'chat-app-5dccc.appspot.com',
    iosBundleId: 'com.example.crazyChat',
  );
}
